---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-calico
  labels:
    app.kubernetes.io/name: test-calico
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-calico
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-calico
        test-calico-access: protected
    spec:
      serviceAccountName: test-calico
      containers:
        - name: test-calico
          image: "nginx:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
