# Keep this in sync with the example in the README.md
---
name: Example
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install K3s
    steps:
      - id: k3s
        uses: manics/action-k3s-helm@main
        with:
          k3s-version: v1.19.3+k3s1
          helm-version: v3.3.4
      - run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl get pods --all-namespaces
          helm list
        shell: bash
