---
name: Test

# yamllint disable-line rule:truthy
on:
  - pull_request
  - push

jobs:
  # https://github.com/pre-commit/action
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test_install_k3s:
    runs-on: ubuntu-latest
    name: Test K3s and Helm
    strategy:
      matrix:
        include:
          - k3s: v1.18.8+k3s1
            helm: v3.3.0
          - k3s: v1.17.11+k3s1
            helm: v3.2.4
          - k3s: v1.16.14+k3s1
            helm: v3.1.3
    steps:
      - uses: actions/checkout@v2
      - id: k3s
        uses: ./
        with:
          k3s-version: ${{ matrix.k3s }}
          helm-version: ${{ matrix.helm }}
      # This action should export KUBECONFIG

      - name: Kubectl
        run: |
          kubectl version
          kubectl get pods --all-namespaces
          kubectl get deploy --all-namespaces
        shell: bash

      - name: Helm
        run: |
          helm version
          helm list
        shell: bash

      - name: Install network policies test
        run: helm install test-calico ./test-calico --wait
        shell: bash

      - name: Run network policies test
        run: helm test test-calico --logs
        shell: bash
